version: '3.8'

services:
  secop-node:
    build: .
    container_name: secop-blockchain-node
    ports:
      - "8080:8080"
    environment:
      - NODE_ID=node-1
      - NODE_NAME=SECOP-Node
      - PORT=8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/health"]
      timeout: 10s
      retries: 3
      start_period: 30s
      interval: 30s
