version: '3.8'

services:
  secop-node:
    build: .
    image: secop-blockchain:latest
    container_name: secop-base-node
    ports:
      - "8080:8080"
    environment:
      - NODE_ID=DNP_NODE
      - NODE_ADDRESS=localhost
      - NODE_PORT=8080
    networks:
      - secop-network
    restart: unless-stopped

networks:
  secop-network:
    driver: bridge
